name: blink
services:
  main:
    image: froststevefrost/watcher:0.0.2
    #build:
    #  context: ./watcher
    #  dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      TZ: America/New_York
    volumes:
      - ~/.android/adbkey:/home/watcher/.android/adbkey:ro
      - ~/.android/adbkey.pub:/home/watcher/.android/adbkey.pub:ro
