name: watcher
services:
  main:
    image: ghcr.io/froststevefrost/watcher:0.0.6
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ~/.android/adbkey:/home/watcher/.android/adbkey:ro
      - ~/.android/adbkey.pub:/home/watcher/.android/adbkey.pub:ro
